version: '3.8'

services:
  app:
    build: .
    container_name: GYSD
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"

volumes:
  pgdata:
